language: python
fast_finish: true

python:
  - 3.6
  - 3.7-dev

group: travis_latest

install: pip install -e .[tests]

script: 
  - pytest -sv
  - flake8
  - mypy . --ignore-missing-imports

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
    pytest --cov;
    coveralls;
    fi
