language: python
dist: xenial
group: travis_latest

git:
  depth: 25
  quiet: true

python:
- 3.6
- 3.7
- 3.8-dev

matrix:
  include:
  - os: linux
    python: 3.7
    install: pip install -e .[tests,cov]
    script:
    - flake8
    - mypy . --ignore-missing-imports
    after_success:
    - pytest --cov
    - coveralls
  - os: osx
    language: minimal
    install: pip3 install -e .[tests]
# temp disable travis bug
#  - os: windows
#    language: minimal
#    before_install:
#    - choco install python3
#    - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"

install: pip install -e .[tests]

script: pytest -rsv
